### ISSUE TITLE
comparisons that constrain the type

### ISSUE THREAD

**Issue by cehteh** [disiamylborane/ranged_integers#2]
Just and idea i may eventually send a PR, for now i just write down some draft/brainfart here asking for your opinion:

Currently math operations yield a new type (ranges) for their result. Eventually it would be useful to have the same for comparisons.

Example:
```
let a: Ranged<0, 100> = ...;
let b: Ranged<20, 30> = ...;

match a.is_less_or_equal_than(b) {
    Ok(a) =>  /* a has now the type Ranged<0, 30> */,
    Err(a) =>  /* a stays as Ranged<0, 100> */
} 

// or

a.is_less_or_equal_than(b)
  .and_then(|a| /*...*/)
  .or_else(|a| /*...*/)
```

Of course similar methods for all other comparisons. 

Bonus: this could/should cause a compile_error rather fail at runtime
```
let a: Ranged<0, 10> = ...;
let b: Ranged<20, 30> = ...;

let new_b = b.is_less_than(a).unwrap();  /*can never happen since b's minimum bound is larger than a's max bound*/
```

i haven't checked if the current const-generics in nightly are capable of all this, but nevertheless i expect these to be improved and stabilized in future.

Edit: let these comparisons return a Result<new_ranged, old_ranged> to be able to handle the failure with chained methods.

**Comment by disiamylborane** [comment]
It's interesting, and it's definitely implementable with the current state of const generics.

For the bonus: I think, it makes sense to add a "nonsense guard" to the ordinary comparison operations too, like:

```rust
let a: Ranged<-30, -10> = ...;
let b: Ranged<20, 30> = ...;
let c: u8 = ...;

if a < b {...}  // Compiler error: a is always less than b
if a > c {...}  // Compiler error: a is never greater than c
```
